# Remote theme directory
# remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Karen Lee
description: "Hi I'm Karen, an experienced Client Manager recently upskilled in the field of Data Science.  My portfolio focuses on interesting projects I've recently undertaken, with a strong emphasis on business impact. Please visit my LinkedIn pages (or download my CV) by using the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "London, UK"
resume_url: /docs/KarenLee CV Jan 2023.docx
avatar_image: /img/squared_photo.png

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/karen-sl-lee/" # Add your linkedln handle
github: "https://leekarensl.github.io/"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
